# Generated by Django 3.0.7 on 2020-06-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('survey_number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
            options={
                'ordering': ['survey_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('identity_number', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['identity_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question_number', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('geolocation_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_survey.GeolocationPerson')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='geolocationperson',
            name='surveyed_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_survey.SurveyedPerson'),
        ),
    ]
